### ISSUE TITLE
Prefix format reserved for internal use

### ISSUE THREAD

**Issue by tkrajina** [tkrajina/gpxpy#117]
Example XML (from @jedie):
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx creator="Garmin Connect" version="1.1"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/11.xsd"
  xmlns:ns3="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
  <metadata>
    <link href="connect.garmin.com">
      <text>Garmin Connect</text>
    </link>
    <time>2018-02-21T14:30:50.000Z</time>
  </metadata>
  <trk>
    <name>Foo Bar</name>
    <type>running</type>
    <trkseg>
      <trkpt lat="51.43788929097354412078857421875" lon="6.617012657225131988525390625">
        <ele>23.6000003814697265625</ele>
        <time>2018-02-21T14:30:50.000Z</time>
        <extensions>
          <ns3:TrackPointExtension>
            <ns3:hr>125</ns3:hr>
            <ns3:cad>75</ns3:cad>
          </ns3:TrackPointExtension>
        </extensions>
      </trkpt>
      <trkpt lat="51.43786800093948841094970703125" lon="6.6170061193406581878662109375">
        <ele>23.6000003814697265625</ele>
        <time>2018-02-21T14:30:51.000Z</time>
        <extensions>
          <ns3:TrackPointExtension>
            <ns3:hr>123</ns3:hr>
            <ns3:cad>75</ns3:cad>
          </ns3:TrackPointExtension>
        </extensions>
      </trkpt>
      <trkpt lat="51.4378472976386547088623046875" lon="6.61700570024549961090087890625">
        <ele>23.799999237060546875</ele>
        <time>2018-02-21T14:30:52.000Z</time>
        <extensions>
          <ns3:TrackPointExtension>
            <ns3:hr>124</ns3:hr>
            <ns3:cad>75</ns3:cad>
          </ns3:TrackPointExtension>
        </extensions>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```
I get this:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    gpx_parser.parse()
  File "gpxpy/gpxpy/parser.py", line 97, in parse
    mod_etree.register_namespace(prefix, URI.strip('"'))
  File "src/lxml/etree.pyx", line 184, in lxml.etree.register_namespace
ValueError: Prefix format reserved for internal use
```

**Comment by tkrajina** [comment]
@jedie I see. I pushed now a temporary branch in `ns-namespace` with a hotfix that should fix it (but it needs more testing).

**Comment by jedie** [comment]
It works here, thanks!

**Comment by jedie** [comment]
@tkrajina Question: Is it possible to the the values by name? e.g.: `point.extensions.get("hr")`

**Comment by jedie** [comment]
I created https://github.com/tkrajina/gpxpy/issues/119 for `point.extensions.get("hr")` ;)
